# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_auto_20170808_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepaSource',
            fields=[
                # ('stripesource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djstripe.StripeSource')),
                ('status', djstripe.fields.StripeCharField(choices=[('pending', 'pending'), ('chargeable', 'chargeable'), ('consumed', 'consumed'), ('canceled', 'canceled'), ('failed', 'failed')], max_length=255)),
                ('client_secret', djstripe.fields.StripeCharField(max_length=255)),
                ('currency', djstripe.fields.StripeCharField(max_length=255)),
                ('usage', djstripe.fields.StripeCharField(max_length=255)),
                ('bank_code', djstripe.fields.StripeCharField(max_length=255)),
                ('country', djstripe.fields.StripeCharField(max_length=255)),
                ('last4', djstripe.fields.StripeCharField(max_length=255)),
                ('mandate_reference', djstripe.fields.StripeCharField(max_length=255)),
                ('mandate_url', djstripe.fields.StripeURLField()),
            ],
            options={
                'abstract': False,
            },
            # bases=('djstripe.stripesource',),
        ),
        migrations.AlterField(
            model_name='charge',
            name='source_type',
            field=djstripe.fields.StripeCharField(choices=[('alipay_account', 'Alipay account'), ('bank_account', 'Bank account'), ('bitcoin_receiver', 'Bitcoin receiver'), ('card', 'Card'), ('sepa_debit', 'Sepa Debit')], help_text='The payment source type. If the payment source is supported by dj-stripe, a corresponding model is attached to this Charge via a foreign key matching this field.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source_type',
            field=djstripe.fields.StripeCharField(choices=[('alipay_account', 'Alipay account'), ('bank_account', 'Bank account'), ('bitcoin_receiver', 'Bitcoin receiver'), ('card', 'Card'), ('sepa_debit', 'Sepa Debit')], help_text='The source balance from which this transfer came.', max_length=16),
        ),
    ]
