# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:26
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_auto_20170827_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='fraud_details',
            field=djstripe.fields.StripeJSONField(default={}, help_text='Hash with information on fraud assessments for the charge.'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='outcome',
            field=djstripe.fields.StripeJSONField(default={}, help_text='Details about whether or not the payment was accepted, and why.'),
        ),
    ]
