# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0013_remove_card_stripe_id_default'),
        ('djstripe', '0013_auto_20170827_0926'),
    ]

    operations = [
    ]
