# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0014_merge_20171217_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SepaSource',
        ),
        migrations.AlterField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='djstripe.Customer'),
        ),
    ]
