# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0015_auto_20171217_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepaSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', djstripe.fields.StripeIdField(max_length=255, unique=True)),
                ('livemode', djstripe.fields.StripeNullBooleanField(default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.')),
                ('stripe_timestamp', djstripe.fields.StripeDateTimeField(help_text='The datetime this object was created in stripe.', null=True)),
                ('metadata', djstripe.fields.StripeJSONField(blank=True, help_text='A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.', null=True)),
                ('description', djstripe.fields.StripeTextField(blank=True, help_text='A description of this object.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', djstripe.fields.StripeCharField(choices=[('pending', 'pending'), ('chargeable', 'chargeable'), ('consumed', 'consumed'), ('canceled', 'canceled'), ('failed', 'failed')], max_length=255)),
                ('client_secret', djstripe.fields.StripeCharField(max_length=255)),
                ('currency', djstripe.fields.StripeCharField(max_length=255)),
                ('usage', djstripe.fields.StripeCharField(max_length=255)),
                ('bank_code', djstripe.fields.StripeCharField(max_length=255)),
                ('country', djstripe.fields.StripeCharField(max_length=255)),
                ('last4', djstripe.fields.StripeCharField(max_length=255)),
                ('mandate_reference', djstripe.fields.StripeCharField(max_length=255)),
                ('mandate_url', djstripe.fields.StripeURLField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='djstripe.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
