# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 14:45
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0020_auto_20180110_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='statement_descriptor',
            field=djstripe.fields.StripeCharField(blank=True, help_text='Extra information about a source. This will appear on your customer\u2019s statement every time you charge the source.', max_length=255, null=True),
        ),
    ]
