# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0031_auto_20170606_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepaSource',
            fields=[
                ('stripesource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djstripe.StripeSource')),
                ('status', models.CharField(choices=[(b'pending', b'pending'), (b'chargeable', b'chargeable'), (b'consumed', b'consumed'), (b'canceled', b'canceled'), (b'failed', b'failed')], max_length=255, verbose_name='Status')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client secret')),
                ('currency', models.CharField(max_length=32, verbose_name='Currency code')),
                ('usage', models.CharField(max_length=255, verbose_name='Usage')),
                ('bank_code', models.CharField(max_length=255, verbose_name='Bank Code')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('last4', models.CharField(max_length=255, verbose_name='Last 4')),
                ('mandate_reference', models.CharField(max_length=255, verbose_name='Mandate reference')),
                ('mandate_url', models.URLField(max_length=255, verbose_name='Mandate URL')),
            ],
            options={
                'abstract': False,
            },
            bases=('djstripe.stripesource',),
        ),

    ]
