# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 01:36
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0033_auto_20170730_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepasource',
            name='currency',
            field=djstripe.fields.StripeCharField(max_length=255),
        ),
    ]
